#! /bin/sh

#Autostart
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
nm-applet &
#nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
numlockx on &
caffeine &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfce4-power-manager &
#bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

#pywal
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config border_width 2
bspc config window_gap 6
bspc config pointer_follows_focus true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
[ "$1" = 0 ] && wmname LG3D
